feat: see intermediate file genb, fix issue with hex literals

diff --git a/src/bcc b/src/bcc
--- a/src/bcc
+++ b/src/bcc
@@ -1,3 +1,8 @@
 #!/bin/bash
 winpty python ./bc/bc.py --verbose --btap $1.b
+retVal=$?
+if [ $retVal -ne 0 ]; then
+    echo "Error"
+    exit $retVal
+fi
 winpty python ./bc81asmc/bc81asmc.py --verbose --btap $1.basm
