fix: small improvements when testing << operator

diff --git a/src/makedisk b/src/makedisk
--- a/src/makedisk
+++ b/src/makedisk
@@ -1,52 +1,42 @@
 #!/bin/bash
+trap "exit 1" TERM
+export TOP_PID=$$
+
+check_exit_code()
+{
+    if [ $1 -ne 0 ]; then
+        echo "Error"
+        kill -s TERM $TOP_PID
+    fi
+}
+
 echo building bootloader...
 winpty python ./bc81asmc/bc81asmc.py --verbose ./bdos/boot.basm
-retVal=$?
-if [ $retVal -ne 0 ]; then
-    echo "Error"
-    exit $retVal
-fi
+check_exit_code $?
+
 echo building bdos...
 ./bcc ./bdos/bdos
-retVal=$?
-if [ $retVal -ne 0 ]; then
-    echo "Error"
-    exit $retVal
-fi
+check_exit_code $?
+
 echo creating os disk...
 echo converting bootloader to sectors...
 ./ftool btap2bin bdos/boot.btap bdos/boot.sector
-retVal=$?
-if [ $retVal -ne 0 ]; then
-    echo "Error"
-    exit $retVal
-fi
+check_exit_code $?
+
 echo converting bdos to sectors...
 ./ftool btap2bin bdos/bdos.btap bdos/bdos.sector
-retVal=$?
-if [ $retVal -ne 0 ]; then
-    echo "Error"
-    exit $retVal
-fi
+check_exit_code $?
+
 echo creating empty floppy disk
-./ftool createbdd bdos/bdos.bdd
-retVal=$?
-if [ $retVal -ne 0 ]; then
-    echo "Error"
-    exit $retVal
-fi
+./ftool createbdd os.bdd
+check_exit_code $?
+
 echo burning boot loader to track 0 sector 0
-./ftool importsector bdos/boot.sector bdos/bdos.bdd 0 0
-retVal=$?
-if [ $retVal -ne 0 ]; then
-    echo "Error"
-    exit $retVal
-fi
+./ftool importsector bdos/boot.sector os.bdd 0 0
+check_exit_code $?
+
 echo burning bdos shell to tracks 0-5
-./ftool importsector bdos/bdos.sector bdos/bdos.bdd 0 1
-retVal=$?
-if [ $retVal -ne 0 ]; then
-    echo "Error"
-    exit $retVal
-fi
+./ftool importsector bdos/bdos.sector os.bdd 0 1
+check_exit_code $?
+
 echo done!
